/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author BV3018229
 */
public class Calculadora extends javax.swing.JFrame {

    boolean first = true;
    double n1;
    double n2;
    int operador;
    
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFTela = new javax.swing.JTextField();
        jBotao7 = new javax.swing.JButton();
        jBotao9 = new javax.swing.JButton();
        jBotao8 = new javax.swing.JButton();
        jBotao5 = new javax.swing.JButton();
        jBotao6 = new javax.swing.JButton();
        jBotao4 = new javax.swing.JButton();
        jBotao1 = new javax.swing.JButton();
        jBotao2 = new javax.swing.JButton();
        jBotao3 = new javax.swing.JButton();
        jBotao0 = new javax.swing.JButton();
        jBotaoIgual = new javax.swing.JButton();
        jBotaoDivide = new javax.swing.JButton();
        jBotaoMenos = new javax.swing.JButton();
        jBotaoVezes = new javax.swing.JButton();
        jBotaoMais = new javax.swing.JButton();
        jBotaoVirgula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTFTela.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jTFTela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFTela.setText("0"); // NOI18N
        jTFTela.setToolTipText("");
        jTFTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFTelaActionPerformed(evt);
            }
        });

        jBotao7.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotao7.setText("7");
        jBotao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao7ActionPerformed(evt);
            }
        });

        jBotao9.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotao9.setText("9");
        jBotao9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao9ActionPerformed(evt);
            }
        });

        jBotao8.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotao8.setText("8");
        jBotao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao8ActionPerformed(evt);
            }
        });

        jBotao5.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotao5.setText("5");
        jBotao5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao5ActionPerformed(evt);
            }
        });

        jBotao6.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotao6.setText("6");
        jBotao6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao6ActionPerformed(evt);
            }
        });

        jBotao4.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotao4.setText("4");
        jBotao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao4ActionPerformed(evt);
            }
        });

        jBotao1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotao1.setText("1");
        jBotao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao1ActionPerformed(evt);
            }
        });

        jBotao2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotao2.setText("2");
        jBotao2.setMinimumSize(new java.awt.Dimension(64, 64));
        jBotao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao2ActionPerformed(evt);
            }
        });

        jBotao3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotao3.setText("3");
        jBotao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao3ActionPerformed(evt);
            }
        });

        jBotao0.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotao0.setText("0");
        jBotao0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotao0ActionPerformed(evt);
            }
        });

        jBotaoIgual.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotaoIgual.setText("=");
        jBotaoIgual.setMaximumSize(new java.awt.Dimension(64, 64));
        jBotaoIgual.setMinimumSize(new java.awt.Dimension(64, 64));
        jBotaoIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoIgualActionPerformed(evt);
            }
        });

        jBotaoDivide.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotaoDivide.setText("/");
        jBotaoDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoDivideActionPerformed(evt);
            }
        });

        jBotaoMenos.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotaoMenos.setText("-");
        jBotaoMenos.setMaximumSize(new java.awt.Dimension(38, 25));
        jBotaoMenos.setMinimumSize(new java.awt.Dimension(38, 25));
        jBotaoMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoMenosActionPerformed(evt);
            }
        });

        jBotaoVezes.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotaoVezes.setText("*");
        jBotaoVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoVezesActionPerformed(evt);
            }
        });

        jBotaoMais.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotaoMais.setText("+");
        jBotaoMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoMaisActionPerformed(evt);
            }
        });

        jBotaoVirgula.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jBotaoVirgula.setText(",");
        jBotaoVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotaoVirgulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBotao0, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotaoVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBotao7, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jBotao1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBotao4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBotao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBotao5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBotao8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBotao9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBotao6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jTFTela))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBotaoIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBotaoMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBotaoMais, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBotaoVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBotaoDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotaoDivide, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(jTFTela, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBotao8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotao7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBotao9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBotaoVezes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBotao5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBotao6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBotaoMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBotao4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBotao1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBotao3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBotaoMais, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBotaoIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotao0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBotaoVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFTelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFTelaActionPerformed

    private void jBotao0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao0ActionPerformed
        // TODO add your handling code here:
        if(first){
            jTFTela.setText("");
            first = false;
        }
        jTFTela.setText(jTFTela.getText() + jBotao0.getText());
    }//GEN-LAST:event_jBotao0ActionPerformed

    private void jBotao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao1ActionPerformed
        // TODO add your handling code here:
        if(first){
            jTFTela.setText("");
            first = false;
        }
        jTFTela.setText(jTFTela.getText() + jBotao1.getText());
    }//GEN-LAST:event_jBotao1ActionPerformed

    private void jBotao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao2ActionPerformed
        // TODO add your handling code here:
        if(first){
            jTFTela.setText("");
            first = false;
        }
        jTFTela.setText(jTFTela.getText() + jBotao2.getText());
    }//GEN-LAST:event_jBotao2ActionPerformed

    private void jBotao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao3ActionPerformed
        // TODO add your handling code here:
        if(first){
            jTFTela.setText("");
            first = false;
        }
        jTFTela.setText(jTFTela.getText() + jBotao3.getText());
    }//GEN-LAST:event_jBotao3ActionPerformed

    private void jBotao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao4ActionPerformed
        // TODO add your handling code here:
        if(first){
            jTFTela.setText("");
            first = false;
        }
        jTFTela.setText(jTFTela.getText() + jBotao4.getText());
    }//GEN-LAST:event_jBotao4ActionPerformed

    private void jBotao5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao5ActionPerformed
        // TODO add your handling code here:
        if(first){
            jTFTela.setText("");
            first = false;
        }
        jTFTela.setText(jTFTela.getText() + jBotao5.getText());
    }//GEN-LAST:event_jBotao5ActionPerformed

    private void jBotao6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao6ActionPerformed
        // TODO add your handling code here:
        if(first){
            jTFTela.setText("");
            first = false;
        }
        jTFTela.setText(jTFTela.getText() + jBotao6.getText());
    }//GEN-LAST:event_jBotao6ActionPerformed

    private void jBotao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao7ActionPerformed
        // TODO add your handling code here:
        if(first){
            jTFTela.setText("");
            first = false;
        }
        jTFTela.setText(jTFTela.getText() + jBotao7.getText());
    }//GEN-LAST:event_jBotao7ActionPerformed

    private void jBotao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao8ActionPerformed
        // TODO add your handling code here:
        if(first){
            jTFTela.setText("");
            first = false;
        }
        jTFTela.setText(jTFTela.getText() + jBotao8.getText());
    }//GEN-LAST:event_jBotao8ActionPerformed

    private void jBotao9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotao9ActionPerformed
        // TODO add your handling code here:
        if(first){
            jTFTela.setText("");
            first = false;
        }
        jTFTela.setText(jTFTela.getText() + jBotao9.getText());
    }//GEN-LAST:event_jBotao9ActionPerformed

    private void jBotaoDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoDivideActionPerformed
        // TODO add your handling code here:
        if(n1 != 0 && n1 != Double.parseDouble(jTFTela.getText())){
            jBotaoIgualActionPerformed(evt);   
        }
            n1 = Double.parseDouble(jTFTela.getText());
            operador = 4;
            first = true;
        
    }//GEN-LAST:event_jBotaoDivideActionPerformed

    private void jBotaoVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoVezesActionPerformed
        if(n1 != 0 && n1 != Double.parseDouble(jTFTela.getText())){
            jBotaoIgualActionPerformed(evt);
            n1 = Double.parseDouble(jTFTela.getText());
            operador = 3;
            first = true;
        }else{
            n1 = Double.parseDouble(jTFTela.getText());
            operador = 3;
            first = true;
        }
    }//GEN-LAST:event_jBotaoVezesActionPerformed

    private void jBotaoMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoMenosActionPerformed
        if(n1 != 0 && n1 != Double.parseDouble(jTFTela.getText())){
            jBotaoIgualActionPerformed(evt);
            n1 = Double.parseDouble(jTFTela.getText());
            operador = 2;
            first = true;
        }else{
            n1 = Double.parseDouble(jTFTela.getText());
            operador = 2;
            first = true;
        }
    }//GEN-LAST:event_jBotaoMenosActionPerformed

    private void jBotaoMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoMaisActionPerformed
        if(n1 != 0 && n1 != Double.parseDouble(jTFTela.getText())){
            jBotaoIgualActionPerformed(evt);
            n1 = Double.parseDouble(jTFTela.getText());
            operador = 1;
            first = true;
        }else{
            n1 = Double.parseDouble(jTFTela.getText());
            operador = 1;
            first = true;
        }
    }//GEN-LAST:event_jBotaoMaisActionPerformed

    private void jBotaoIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoIgualActionPerformed
        // TODO add your handling code here:
        n2 = Double.parseDouble(jTFTela.getText());
        jTFTela.setText(Double.toString(operacoes(n1, n2, operador)));
        n1 = 0;
        n2 = 0;
    }//GEN-LAST:event_jBotaoIgualActionPerformed

    private void jBotaoVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotaoVirgulaActionPerformed
        // TODO add your handling code here:
        jTFTela.setText(jTFTela.getText() + ".");
    }//GEN-LAST:event_jBotaoVirgulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Calculadora window = new Calculadora();
                window.setResizable(false);
                window.setTitle("Calculadora");
                window.setVisible(true);
            }
        });
    }
    
    private double operacoes(double n1, double n2, int op){
        switch(op){
            case 1:
                return n1 + n2;
            case 2:
                return n1 - n2;
            case 3:
                return n1 * n2;
            case 4:
                return n1 / n2;
            default:
                return 0;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotao0;
    private javax.swing.JButton jBotao1;
    private javax.swing.JButton jBotao2;
    private javax.swing.JButton jBotao3;
    private javax.swing.JButton jBotao4;
    private javax.swing.JButton jBotao5;
    private javax.swing.JButton jBotao6;
    private javax.swing.JButton jBotao7;
    private javax.swing.JButton jBotao8;
    private javax.swing.JButton jBotao9;
    private javax.swing.JButton jBotaoDivide;
    private javax.swing.JButton jBotaoIgual;
    private javax.swing.JButton jBotaoMais;
    private javax.swing.JButton jBotaoMenos;
    private javax.swing.JButton jBotaoVezes;
    private javax.swing.JButton jBotaoVirgula;
    private javax.swing.JTextField jTFTela;
    // End of variables declaration//GEN-END:variables
}
